### ISSUE TITLE
Unable to capture traffic to/from web server

### ISSUE THREAD

**Issue by yasir-ss** [qpoint-io/qtap#29]
I'm unable to see any logs for traffic to/from a web server.

Here's how I run the web server:
```
python3 -m http.server 80
```

Here's how I run qtap:
```
./bin/qtap
```

I don't see any logs in the qtap console when I send an HTTP request to the web server either from the same host or a different host. Does qtap support this use case?

**Comment by Devin-qpoint** [comment]
Hey there,

Yes, this is definitely possible.

By default, Qtap is configured to monitor egress (outbound) traffic only. To monitor incoming traffic to your web server, you need to explicitly configure Qtap to capture bidirectional traffic.

### Step 1: Create a proper configuration file

Create a file named `qtap-config.yaml` with the following content:

```yaml
version: 2
services:
  event_stores:
    - id: console_stdout
      type: stdout
  object_stores:
    - id: console_stdout
      type: stdout
stacks:
  default_stack:
    plugins:
      - type: access_logs
        config:
          mode: details     # (summary|details|full)
          format: console   # (json|console)
tap:
  direction: all            # (all|ingress|egress|egress-external|egress-internal)
  ignore_loopback: false    # Ensure localhost traffic is captured
  audit_include_dns: true
  http:
    stack: default_stack
```

The most important settings here are:
- `direction: all` - This captures both incoming and outgoing traffic
- `ignore_loopback: false` - This ensures traffic to/from 127.0.0.1 is captured

### Step 2: Run Qtap with your configuration

```bash
sudo ./bin/qtap --config=./qtap-config.yaml
```

Note that you need to run Qtap with sudo/root privileges for eBPF to work properly.

### Step 3: Test your setup

1. Keep your Python web server running in one terminal:
   ```bash
   sudo python3 -m http.server 80
   ```

2. Send an HTTP request to your web server from another terminal:
   ```bash
   curl http://127.0.0.1:80
   ```

You should now see both sides of the connection in Qtap logs:
- The egress connection (from curl to the web server)
- The ingress connection (the Python web server handling the request)

### Expected Output

You should see two log entries for each request, something like:

```
■ curl → GET http://127.0.0.1/ 200 OK
■ python3 ← GET http://127.0.0.1/ 200 OK
```
