### ISSUE TITLE
S3 Integration

### ISSUE THREAD

**Issue by vbisbest** [qpoint-io/qtap#54]
I am able to capture events and objects just fine.  But I cant figure out how the S3 integration works.  I have the section defined in my config under object_stores.   But I am not seeing any attempt to actually push anything to my s3 bucket.  No errors, nothing.   Here is my config

`version: 2
  services:
    event_stores:
      - id: console_stdout
        type: disabled
    object_stores:
      - id: aws_s3
        type: s3    
        region: us-east-2    
        endpoint: s3.amazonaws.com
        bucket: MYBUCKET   
        prefix: http   
        access_url: https://s3.amazonaws.com/{{BUCKET}}/{{DIGEST}}        
        insecure: false
        access_key:
          type: end
          value: key
        secret_key:
          type: env
          value: secret        
  stacks:
    default_stack: # Stack Name
      plugins:
        - type: access_logs
          config:
            mode: full # Default action (summary|details|full)
            format: json # (json|console)
            oabject_store: aws_s3
  podAnnotations:
    qtap/restartedAt: "{{ now | quote }}"            
  tap:
    direction: egress-internal # (all|ingress|egress|egress-external|egress-internal)
    ignore_loopback: true
    audit_include_dns: false
    http:
      stack: default_stack
    filters:
      groups:
        - qpoint
        - kubernetest
        - minikube
        - qpoint
    method:
      - GET
      - POST`

**Comment by Devin-qpoint** [comment]
Hey there,

Try this! For reference, the docs [here](https://docs.qpoint.io/qtap/configuration/storage-configuration) should outline everything.

Fixes Applied:

**Typo in access_key: type**: end → type: env
**Removed object_store directive**: Deleted object_store: aws_s3 from the plugin config (not needed when you only have one object store)

```yaml
version: 2

services:
  event_stores:
    - id: console_stdout
      type: disabled
  
  object_stores:
    - id: aws_s3
      type: s3
      endpoint: s3.amazonaws.com
      bucket: my-company-qpoint
      region: us-west-2
      access_url: https://s3.amazonaws.com/{{BUCKET}}/{{DIGEST}}
      insecure: false
      access_key:
        type: env
        value: AWS_ACCESS_KEY_ID
      secret_key:
        type: env
        value: AWS_SECRET_ACCESS_KEY

stacks:
  default_stack:
    plugins:
      - type: access_logs
        config:
          mode: full
          format: json

tap:
  direction: egress-internal
  ignore_loopback: true
  audit_include_dns: false
  http:
    stack: default_stack
```

Make sure you have those AWS environment variables set and the bucket should start receiving objects when traffic is captured.

# Check if variables are set
echo $AWS_ACCESS_KEY_ID
echo $AWS_SECRET_ACCESS_KEY

**Comment by vbisbest** [comment]
I have all this setup and its still not working.  Verified env variables are correct.   I even messed up the endpoint and access_url values and there are no errors in the logs.  It just seems to be ignoring the s3 section all together.

**Comment by Devin-qpoint** [comment]
Does anything bubble up when you set the log level to debug?

`--log-level=debug`

**Comment by Devin-qpoint** [comment]
Could you also try another plugin? 

```yaml
version: 2

services:
  event_stores:
    - id: console_stdout
      type: disabled
  
  object_stores:
    - id: aws_s3
      type: s3
      endpoint: s3.amazonaws.com
      bucket: my-company-qpoint
      region: us-west-2
      access_url: https://s3.amazonaws.com/{{BUCKET}}/{{DIGEST}}
      insecure: false
      access_key:
        type: env
        value: AWS_ACCESS_KEY_ID
      secret_key:
        type: env
        value: AWS_SECRET_ACCESS_KEY

stacks:
  default_stack:
    plugins:
      - type: detect_errors
        config:
          rules:
            - name: Debug
              trigger_status_codes:
                - '2xx'
                - '3xx'
                - '4xx'
                - '5xx'
              only_categories:
                - app
              report_as_issue: false
              record_req_headers: true
              record_req_body: true
              record_res_headers: true
              record_res_body: true

tap:
  direction: egress-internal
  ignore_loopback: true
  audit_include_dns: false
  http:
    stack: default_stack
```
