### ISSUE TITLE
Rule panic

### ISSUE THREAD

**Issue by vbisbest** [qpoint-io/qtap#55]
When setting a rule for user-agent, qtap panics:

config:

```yaml
stacks:
    default_stack: # Stack Name
      plugins:
        - type: access_logs
          config:
            mode: full # Default action (summary|details|full)
            format: json # (json|console)
            rules:
            - name: ignore kube-probe
              expr: request.header.user-agent == "kube-probe/1.32"  
              mode: none
```

```json
 {"level":"error","ts":1747743357.3190467,"message":"Panic in Destroy","plugin":"access_logs","panic":"runtime error: invalid memory address or nil pointer dereference","stacktrace":"github.com/qpoint-io/qtap/pkg/plugins/wrapper.(*SafeHttpFilterInstance).Destroy.func1\n\t/go/pkg/mod/github.com/qpoint-io/qtap@v0.0.0-20250514170630-cbeb643d1cc4/pkg/plugins/wrapper/wrapper.go:132\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:792\nruntime.panicmem\n\t/usr/local/go/src/runtime/panic.go:262\nruntime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:925\ngithub.com/qpoint-io/qtap/pkg/plugins/accesslogs.(*filterInstance).Destroy\n\t/go/pkg/mod/github.com/qpoint-io/qtap@v0.0.0-20250514170630-cbeb643d1cc4/pkg/plugins/accesslogs/access_logs_http.go:99\ngithub.com/qpoint-io/qtap/pkg/plugins/wrapper.(*SafeHttpFilterInstance).Destroy\n\t/go/pkg/mod/github.com/qpoint-io/qtap@v0.0.0-20250514170630-cbeb643d1cc4/pkg/plugins/wrapper/wrapper.go:138\ngithub.com/qpoint-io/qtap/pkg/plugins.(*Connection).Teardown\n\t/go/pkg/mod/github.com/qpoint-io/qtap@v0.0.0-20250514170630-cbeb643d1cc4/pkg/plugins/connection.go:76\ngithub.com/qpoint-io/qtap/pkg/stream/protocols/http1.(*Session).Close\n\t/go/pkg/mod/github.com/qpoint-io/qtap@v0.0.0-20250514170630-cbeb643d1cc4/pkg/stream/protocols/http1/session.go:318\ngithub.com/qpoint-io/qtap/pkg/stream/protocols/http1.(*Session).Run\n\t/go/pkg/mod/github.com/qpoint-io/qtap@v0.0.0-20250514170630-cbeb643d1cc4/pkg/stream/protocols/http1/session.go:113"}  
```
