### ISSUE TITLE
Unable to see HTTP requests

### ISSUE THREAD

**Issue by kgal-akl** [qpoint-io/qtap#82]
I installed QTap using the `helm` chart into my k3s server:

```bash
helm install qtap qpoint/qtap --namespace qtap --create-namespace -f deploy/qtap/values.yaml
```

Here's the `values.yaml` I used, got it from `helm show values qpoint/qtap > values.yaml`:

```yaml
# Default values for qtap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: us-docker.pkg.dev/qpoint-edge/public/qtap
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

args: []

registrationEndpoint: "https://api.qpoint.io"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  # fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: true
  capabilities:
    add: ["CAP_BPF", "CAP_SYS_ADMIN"]
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0
  privileged: true

# One of debug, info, warn, error, dpanic, panic, fatal
logLevel: "info"

# One of console, json
logEncoding: "json"

status:
  addr: 0.0.0.0
  port: 10001

middlewareEgress:
  addr: 127.0.0.1
  port: 11001

# The following resources are used for the tap pod. They need to be adjusted to your needs and based
# on the resources available on your cluster.
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

# Additional volumes on the output Deployment definition.
volumes:
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false
  - name: sys
    hostPath:
      # Ensure the file directory is created.
      path: /sys
      type: Directory

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true
  - name: sys
    mountPath: "/sys"
    readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

integrations:
  containerd:
    enabled: true
    hostSocketPath: /run/containerd/containerd.sock

# API token
registrationToken: "$MY_TOKEN"
# OR
# registrationTokenSecretRefName: ""

config: ""
# config: |
#   stacks: {}
#   tap:
#     default_stack: "example"
#     default_domain_action: IGNORE # default capture action
#     endpoints: []
#   # Proxy configurations
#   proxy:
#     jwt_hmac_key: "qwertyuiopasdfghjklzxcvbnm123456"
#     default_domain_action: ALLOW
#     endpoints: []

# Additional environment variables for the DaemonSet
extraEnv: []
# extraEnv:
#   - name: BPF_TRACE
#     value: "mod:openssl,mod:protocol,exe.contains:curl"
#   - name: SOME_ENV_VAR
#     valueFrom:
#       secretKeyRef:
#       name: some-secret
#       key: some-key
#   - name: TLS_PROBES
#     value: "openssl"
```

I can see almost all data when I log into https://app.qpoint.io/ except for HTTP requests:

<img width="1678" alt="Image" src="https://github.com/user-attachments/assets/c01c8fda-4cbf-4edf-bd14-0bafad43aac2" />
