### ISSUE TITLE
Qtap pod unable to connect to minio

### ISSUE THREAD

**Issue by vakhariad** [qpoint-io/qtap#84]
Hi,
I am trying to publish data to minio object store. I have deployed minio using helm chart(latest). Below is the config that i am using to create qtap pod. But its not connecting to minio.

```
extraEnv:
  - name: MINIO_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: minio-credentials
        key: MINIO_ACCESS_KEY
  - name: MINIO_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: minio-credentials
        key: MINIO_SECRET_KEY

# The main qtap configuration remains the same.
config: |
  version: 2
  services:
    event_stores:
      - id: console_stdout
        type: stdout
    
    object_stores:
      - id: minio
        type: s3
        endpoint: http://minio.minio-dev.svc.cluster.local:9000
        bucket: test-qtap
        region: us-east-1
        access_url: http://minio.minio-dev.svc.cluster.local:9000/{{BUCKET}}/{{DIGEST}}
        insecure: true
        access_key:
          type: env
          value: MINIO_ACCESS_KEY
        secret_key:
          type: env
          value: MINIO_SECRET_KEY
```

Logs are as follow:
```
{"level":"info","ts":1749201717.1700923,"message":"config load completed"}
{"level":"info","ts":1749201721.3432822,"message":"connected to containerd","package":"container","path":"/run/containerd/containerd.sock"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0xaf7246]

goroutine 79 [running]:
github.com/qpoint-io/qtap/pkg/plugins.(*Manager).SetConfig(0xc0022d4d80, 0xc0003f45a0)
	/go/pkg/mod/github.com/qpoint-io/qtap@v0.0.0-20250603160046-90f65a7b4df3/pkg/plugins/manager.go:125 +0x46
github.com/qpoint-io/qpoint/internal/cmd.runTapCmd.(*ConfigManager).SubscribeSetter.func18(0xc000160948?)
	/go/pkg/mod/github.com/qpoint-io/qtap@v0.0.0-20250603160046-90f65a7b4df3/pkg/config/provider.go:67 +0x22
created by github.com/qpoint-io/qtap/pkg/config.(*ConfigManager).Subscribe in goroutine 1
	/go/pkg/mod/github.com/qpoint-io/qtap@v0.0.0-20250603160046-90f65a7b4df3/pkg/config/provider.go:57 +0x157
```

**Comment by Devin-qpoint** [comment]
Hey there,

We suspect that you haven't defined any plugins. See [this](https://github.com/qpoint-io/qtap/blob/main/examples/sample-capture-minio.yaml) for a great example of how an HTTP capture plugin.

**Comment by kamaln7** [comment]
Hi @vakhariad, in addition to configuring plugins like @Devin-qpoint suggested, please make sure to define the `tap:` section. Let us know if the following config works:

```yaml
# The main qtap configuration remains the same.
config: |
  version: 2
    services:
      event_stores:
        - id: console_stdout
          type: stdout
      
      object_stores:
        - id: minio
          type: s3
          endpoint: http://minio.minio-dev.svc.cluster.local:9000
          bucket: test-qtap
          region: us-east-1
          access_url: http://minio.minio-dev.svc.cluster.local:9000/{{BUCKET}}/{{DIGEST}}
          insecure: true
          access_key:
            type: env
            value: MINIO_ACCESS_KEY
          secret_key:
            type: env
            value: MINIO_SECRET_KEY
    stacks:
      basic_reporting:
        plugins:
          - type: report_usage
          - type: http_capture
            config:
              level: full # (none|summary|details|full)
              format: text # (json|text)
    tap:
      direction: egress # (egress|egress-external|egress-internal)
      ignore_loopback: true
      audit_include_dns: false
      http:
        stack: basic_reporting
```

Edit from @jonfriesen: The report_usage plugin does not save anything to object store. I've added a http_capture which will push http request/responses to the object store.
